title: Constructor Studio Mobile SuperApp Kit
description: 4-level documentation hierarchy for mobile apps with cascading requirements traceability
baseurl: ""
url: "https://teslanika.github.io/studio-kit-mobile-superapp"

theme: null
plugins: []

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

include:
  - index.html
